# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/

version: 2.1

jobs:
  build:
    macos:
      xcode: 14.3.1
    steps:
      - checkout
      - run:
          name: decode Certificates
          command: base64 -D -o Certificates.p12 \<<< $Certificates
      - run:
          name: make Provisioning Profiles directory
          command: mkdir -pv ~/Library/MobileDevice/Provisioning\ Profiles/
      - run:
          name: decode Provisioning Profiles
          command: base64 -D -o ~/Library/MobileDevice/Provisioning\ Profiles/App_Store.mobileprovision \<<< $App_Store_Profile
      - run: bundle exec fastlane clean
      - run:
          name: Build Food App iOS simulator (from examples/FoodApp)
          command: cd examples/FoodApp && xcodebuild -configuration Release -sdk iphonesimulator
      - run:
          name: Build Food App iOS device (from examples/FoodApp)
          command: cd examples/FoodApp && xcodebuild -configuration Release -sdk iphoneos
